# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileencoder.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FileEncoder(object):
    def setupUi(self, FileEncoder):
        FileEncoder.setObjectName("FileEncoder")
        FileEncoder.resize(873, 335)
        self.centralWidget = QtWidgets.QWidget(FileEncoder)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.source_btn = QtWidgets.QPushButton(self.frame)
        self.source_btn.setObjectName("source_btn")
        self.horizontalLayout_3.addWidget(self.source_btn)
        self.source_lbl = QtWidgets.QLineEdit(self.frame)
        self.source_lbl.setReadOnly(True)
        self.source_lbl.setObjectName("source_lbl")
        self.horizontalLayout_3.addWidget(self.source_lbl)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.encoding_lbl = QtWidgets.QLineEdit(self.frame)
        self.encoding_lbl.setReadOnly(True)
        self.encoding_lbl.setObjectName("encoding_lbl")
        self.horizontalLayout_4.addWidget(self.encoding_lbl)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lcd = QtWidgets.QLCDNumber(self.frame)
        self.lcd.setDigitCount(3)
        self.lcd.setObjectName("lcd")
        self.horizontalLayout_4.addWidget(self.lcd)
        self.progress = QtWidgets.QProgressBar(self.frame)
        self.progress.setProperty("value", 0)
        self.progress.setTextVisible(False)
        self.progress.setObjectName("progress")
        self.horizontalLayout_4.addWidget(self.progress)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.destination_btn = QtWidgets.QPushButton(self.frame_2)
        self.destination_btn.setObjectName("destination_btn")
        self.horizontalLayout.addWidget(self.destination_btn)
        self.destination_lbl = QtWidgets.QLineEdit(self.frame_2)
        self.destination_lbl.setReadOnly(True)
        self.destination_lbl.setObjectName("destination_lbl")
        self.horizontalLayout.addWidget(self.destination_lbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.encoding_combo = QtWidgets.QComboBox(self.frame_2)
        self.encoding_combo.setObjectName("encoding_combo")
        self.horizontalLayout_2.addWidget(self.encoding_combo)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.transcode_btn = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.transcode_btn.setFont(font)
        self.transcode_btn.setObjectName("transcode_btn")
        self.horizontalLayout_5.addWidget(self.transcode_btn)
        self.results_lbl = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.results_lbl.setFont(font)
        self.results_lbl.setObjectName("results_lbl")
        self.horizontalLayout_5.addWidget(self.results_lbl)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.frame_3)
        FileEncoder.setCentralWidget(self.centralWidget)

        self.retranslateUi(FileEncoder)
        QtCore.QMetaObject.connectSlotsByName(FileEncoder)

    def retranslateUi(self, FileEncoder):
        _translate = QtCore.QCoreApplication.translate
        FileEncoder.setWindowTitle(_translate("FileEncoder", "FileEncoder"))
        self.label.setText(_translate("FileEncoder", "Select source file:"))
        self.source_btn.setText(_translate("FileEncoder", "Browse..."))
        self.label_4.setText(_translate("FileEncoder", "Encoding detected:"))
        self.label_3.setText(_translate("FileEncoder", "Confidence:"))
        self.label_2.setText(_translate("FileEncoder", "Select destination:"))
        self.destination_btn.setText(_translate("FileEncoder", "Browse..."))
        self.label_5.setText(_translate("FileEncoder", "Select encoding:"))
        self.transcode_btn.setText(_translate("FileEncoder", "Transcode"))
        self.results_lbl.setText(_translate("FileEncoder", "Process results"))

